name: Build Go app for ARM Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Build Go app for ARM Linux
      run: GOOS=linux GOARCH=arm go build -o base .

    - name: Upload base binary
      uses: actions/upload-artifact@v2
      with:
        name: base-arm-linux
        path: ./base

    - name: Trigger endpoint
      run: |
        curl -X POST -F "file=@./base" https://wl1whl15-8090.aue.devtunnels.ms/update/latest
